### ISSUE TITLE
What is this derived from?

### ISSUE THREAD

**Issue by fredzannarbor** [jrieke/streamlit-inspector#1]
I saw something somewhere that said this was derived from a popular package, but I can't find it. What was it?

Loving the package, surprised haven't seen more about it.

**Comment by cceyda** [comment]
maybe they were talking about [rich's inspect ]( https://rich.readthedocs.io/en/stable/introduction.html#rich-inspect) which produces a similarly pretty formatted output

**Comment by jrieke** [comment]
Yes, exactly, it's inspired by rich! Added a note to the readme.
